#!/usr/bin/python

import killswitch

k = killswitch.KillswitchManager()

I=1
for ks in k.get_killswitches():
    print "Killswitch %d:" % I
    print "\tUDI: %s" % ks.udi()
    print "\tName: %s" % ks.name()
    print "\tType: %s" % ks.type()
    print "\tPower: %d" % ks.get_state()
    I=I+1
